### ISSUE TITLE
UnionFind with write:true fails (bricks database)

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-graph-algorithms#86]
```
call algo.unionFind('Person','KNOWS',{write:true});
+--------------------------------------------------------------------+
| loadDuration | evalDuration | writeDuration | nodeCount | setCount |
+--------------------------------------------------------------------+
| 379          | 3            | 239           | 9987      | 1        |
+--------------------------------------------------------------------+
1 row
645 ms
TransactionFailureException: Transaction was marked as successful, but unable to commit transaction so rolled back.

Caused by: org.neo4j.kernel.impl.store.InvalidRecordException: Unknown property type for type 15
	at org.neo4j.kernel.impl.store.PropertyType.getPropertyTypeOrThrow(PropertyType.java:379)
	at org.neo4j.kernel.impl.store.record.PropertyBlock.getType(PropertyBlock.java:56)
	at org.neo4j.kernel.impl.store.record.PropertyBlock.getType(PropertyBlock.java:45)
	at org.neo4j.kernel.impl.api.index.PropertyPhysicalToLogicalConverter.valueOf(PropertyPhysicalToLogicalConverter.java:144)
	at org.neo4j.kernel.impl.api.index.PropertyPhysicalToLogicalConverter.apply(PropertyPhysicalToLogicalConverter.java:81)
	at org.neo4j.kernel.impl.transaction.state.OnlineIndexUpdates.gatherUpdatesFromPropertyCommandsForNode(OnlineIndexUpdates.java:163)
	at org.neo4j.kernel.impl.transaction.state.OnlineIndexUpdates.access$000(OnlineIndexUpdates.java:63)
	at org.neo4j.kernel.impl.transaction.state.OnlineIndexUpdates$1.visited(OnlineIndexUpdates.java:117)
	at org.neo4j.kernel.impl.transaction.state.OnlineIndexUpdates$1.visited(OnlineIndexUpdates.java:113)


org.neo4j.graphdb.TransactionFailureException: Database has encountered some problem, please perform necessary action (tx recovery/restart)
	at org.neo4j.kernel.impl.factory.ClassicCoreSPI.beginTransaction(ClassicCoreSPI.java:181)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransactionInternal(GraphDatabaseFacade.java:578)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransaction(GraphDatabaseFacade.java:383)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTx(GraphDatabaseFacade.java:371)
	at org.neo4j.shell.kernel.GraphDatabaseShellServer.getPrompt(GraphDatabaseShellServer.java:192)
	at org.neo4j.shell.impl.AbstractAppServer.interpretLine(AbstractAppServer.java:128)
	at org.neo4j.shell.kernel.GraphDatabaseShellServer.interpretLine(GraphDatabaseShellServer.java:105)
	at org.neo4j.shell.impl.AbstractClient.evaluate(AbstractClient.java:150)
	at org.neo4j.shell.impl.AbstractClient.evaluate(AbstractClient.java:134)
	at org.neo4j.shell.impl.AbstractClient.grabPrompt(AbstractClient.java:102)
	at org.neo4j.shell.StartClient.grabPromptOrJustExecuteCommand(StartClient.java:417)
	at org.neo4j.shell.StartClient.tryStartLocalServerAndClient(StartClient.java:308)
	at org.neo4j.shell.StartClient.startLocal(StartClient.java:280)
	at org.neo4j.shell.StartClient.start(StartClient.java:213)
	at org.neo4j.shell.StartClient.main(StartClient.java:147)
Caused by: org.neo4j.kernel.api.exceptions.TransactionFailureException: Database has encountered some problem, please perform necessary action (tx recovery/restart)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.neo4j.kernel.internal.DatabaseHealth.assertHealthy(DatabaseHealth.java:62)
	at org.neo4j.kernel.impl.api.Kernel.newTransaction(Kernel.java:99)
	at org.neo4j.kernel.impl.factory.ClassicCoreSPI.beginTransaction(ClassicCoreSPI.java:173)
	... 14 more
Caused by: org.neo4j.kernel.impl.store.InvalidRecordException: Unknown property type for type 15
	at org.neo4j.kernel.impl.store.PropertyType.getPropertyTypeOrThrow(PropertyType.java:379)
	at org.neo4j.kernel.impl.store.record.PropertyBlock.getType(PropertyBlock.java:56)
	at org.neo4j.kernel.impl.store.record.PropertyBlock.getType(PropertyBlock.java:45)
	at org.neo4j.kernel.impl.api.index.PropertyPhysicalToLogicalConverter.valueOf(PropertyPhysicalToLogicalConverter.java:144)
	at org.neo4j.kernel.impl.api.index.PropertyPhysicalToLogicalConverter.apply(PropertyPhysicalToLogicalConverter.java:81)
	at org.neo4j.kernel.impl.transaction.state.OnlineIndexUpdates.gatherUpdatesFromPropertyCommandsForNode(OnlineIndexUpdates.java:163)
	at org.neo4j.kernel.impl.transaction.state.OnlineIndexUpdates.access$000(OnlineIndexUpdates.java:63)
	at org.neo4j.kernel.impl.transaction.state.OnlineIndexUpdates$1.visited(OnlineIndexUpdates.java:117)
	at org.neo4j.kernel.impl.transaction.state.OnlineIndexUpdates$1.visited(OnlineIndexUpdates.java:113)
	at org.neo4j.collection.primitive.hopscotch.PrimitiveLongObjectHashMap.visitEntries(PrimitiveLongObjectHashMap.java:83)
	at org.neo4j.kernel.impl.transaction.state.OnlineIndexUpdates.gatherUpdatesFromPropertyCommands(OnlineIndexUpdates.java:112)
	at org.neo4j.kernel.impl.transaction.state.OnlineIndexUpdates.feed(OnlineIndexUpdates.java:97)
	at org.neo4j.kernel.impl.transaction.command.IndexBatchTransactionApplier$SingleTransactionApplier.close(IndexBatchTransactionApplier.java:147)
	at org.neo4j.kernel.impl.api.TransactionApplierFacade.close(TransactionApplierFacade.java:52)
	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.apply(RecordStorageEngine.java:350)
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.applyToStore(TransactionRepresentationCommitProcess.java:78)
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.commit(TransactionRepresentationCommitProcess.java:51)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:608)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.closeTransaction(KernelTransactionImplementation.java:484)
	at org.neo4j.kernel.api.KernelTransaction.close(KernelTransaction.java:135)
	at org.neo4j.kernel.impl.coreapi.TopLevelTransaction.close(TopLevelTransaction.java:79)
	at org.neo4j.shell.kernel.apps.TransactionProvidingApp.execute(TransactionProvidingApp.java:248)
	at org.neo4j.shell.kernel.apps.cypher.Start.execute(Start.java:80)
	at org.neo4j.shell.impl.AbstractAppServer.interpretLine(AbstractAppServer.java:126)
	... 9 more

```

**Comment by jexp** [comment]
Actually it bricks the database

```
JAVA_OPTS="-Xmx2G -Xms2G" ~/v/neo4j-enterprise-3.1.3/bin/neo4j-shell -path sf001/graph.db/ -config neo4j.conf  -v
ERROR (-v for expanded information):
	Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /Users/mh/support/ldbc/sf001/graph.db
java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /Users/mh/support/ldbc/sf001/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:199)
	at org.neo4j.graphdb.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:36)
	at org.neo4j.graphdb.factory.EnterpriseGraphDatabaseFactory.lambda$createDatabaseCreator$0(EnterpriseGraphDatabaseFactory.java:35)
	at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:183)
	at org.neo4j.shell.kernel.GraphDatabaseShellServer.instantiateGraphDb(GraphDatabaseShellServer.java:213)
	at org.neo4j.shell.kernel.GraphDatabaseShellServer.<init>(GraphDatabaseShellServer.java:75)
	at org.neo4j.shell.StartClient.getGraphDatabaseShellServer(StartClient.java:316)
	at org.neo4j.shell.StartClient.tryStartLocalServerAndClient(StartClient.java:292)
	at org.neo4j.shell.StartClient.startLocal(StartClient.java:280)
	at org.neo4j.shell.StartClient.start(StartClient.java:213)
	at org.neo4j.shell.StartClient.main(StartClient.java:147)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.recovery.Recovery@7d681cb' failed to initialize. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:415)
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
	at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:523)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:100)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:195)
	... 10 more
Caused by: org.neo4j.kernel.impl.store.InvalidRecordException: Unknown property type for type 15
	at org.neo4j.kernel.impl.store.PropertyType.getPropertyTypeOrThrow(PropertyType.java:379)
	at org.neo4j.kernel.impl.store.record.PropertyBlock.getType(PropertyBlock.java:56)
	at org.neo4j.kernel.impl.store.record.PropertyBlock.getType(PropertyBlock.java:45)
	at org.neo4j.kernel.impl.transaction.command.HighIdTransactionApplier.visitPropertyCommand(HighIdTransactionApplier.java:85)
```
